// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services/account/proto/account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{0}
}
func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (dst *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(dst, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Account struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Email                string            `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Addresses            []*Address        `protobuf:"bytes,4,rep,name=addresses" json:"addresses,omitempty"`
	ConfirmToken         string            `protobuf:"bytes,5,opt,name=confirm_token,json=confirmToken" json:"confirm_token,omitempty"`
	PasswordResetToken   string            `protobuf:"bytes,6,opt,name=password_reset_token,json=passwordResetToken" json:"password_reset_token,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,7,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{1}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetAddresses() []*Address {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *Account) GetConfirmToken() string {
	if m != nil {
		return m.ConfirmToken
	}
	return ""
}

func (m *Account) GetPasswordResetToken() string {
	if m != nil {
		return m.PasswordResetToken
	}
	return ""
}

func (m *Account) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ListAccountsRequest struct {
	PageSize             int32    `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken            string   `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{2}
}
func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (dst *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(dst, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAccountsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts" json:"accounts,omitempty"`
	NextPageToken        string     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{3}
}
func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (dst *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(dst, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *ListAccountsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetByIdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIdRequest) Reset()         { *m = GetByIdRequest{} }
func (m *GetByIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIdRequest) ProtoMessage()    {}
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{4}
}
func (m *GetByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIdRequest.Unmarshal(m, b)
}
func (m *GetByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIdRequest.Marshal(b, m, deterministic)
}
func (dst *GetByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIdRequest.Merge(dst, src)
}
func (m *GetByIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIdRequest.Size(m)
}
func (m *GetByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIdRequest proto.InternalMessageInfo

func (m *GetByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByEmailRequest) Reset()         { *m = GetByEmailRequest{} }
func (m *GetByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*GetByEmailRequest) ProtoMessage()    {}
func (*GetByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{5}
}
func (m *GetByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByEmailRequest.Unmarshal(m, b)
}
func (m *GetByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByEmailRequest.Marshal(b, m, deterministic)
}
func (dst *GetByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByEmailRequest.Merge(dst, src)
}
func (m *GetByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_GetByEmailRequest.Size(m)
}
func (m *GetByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByEmailRequest proto.InternalMessageInfo

func (m *GetByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type AuthenticateByEmailRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateByEmailRequest) Reset()         { *m = AuthenticateByEmailRequest{} }
func (m *AuthenticateByEmailRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateByEmailRequest) ProtoMessage()    {}
func (*AuthenticateByEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{6}
}
func (m *AuthenticateByEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateByEmailRequest.Unmarshal(m, b)
}
func (m *AuthenticateByEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateByEmailRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateByEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateByEmailRequest.Merge(dst, src)
}
func (m *AuthenticateByEmailRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateByEmailRequest.Size(m)
}
func (m *AuthenticateByEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateByEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateByEmailRequest proto.InternalMessageInfo

func (m *AuthenticateByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthenticateByEmailRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GeneratePasswordTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratePasswordTokenRequest) Reset()         { *m = GeneratePasswordTokenRequest{} }
func (m *GeneratePasswordTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GeneratePasswordTokenRequest) ProtoMessage()    {}
func (*GeneratePasswordTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{7}
}
func (m *GeneratePasswordTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratePasswordTokenRequest.Unmarshal(m, b)
}
func (m *GeneratePasswordTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratePasswordTokenRequest.Marshal(b, m, deterministic)
}
func (dst *GeneratePasswordTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratePasswordTokenRequest.Merge(dst, src)
}
func (m *GeneratePasswordTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GeneratePasswordTokenRequest.Size(m)
}
func (m *GeneratePasswordTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratePasswordTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratePasswordTokenRequest proto.InternalMessageInfo

func (m *GeneratePasswordTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GeneratePasswordTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneratePasswordTokenResponse) Reset()         { *m = GeneratePasswordTokenResponse{} }
func (m *GeneratePasswordTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GeneratePasswordTokenResponse) ProtoMessage()    {}
func (*GeneratePasswordTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{8}
}
func (m *GeneratePasswordTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratePasswordTokenResponse.Unmarshal(m, b)
}
func (m *GeneratePasswordTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratePasswordTokenResponse.Marshal(b, m, deterministic)
}
func (dst *GeneratePasswordTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratePasswordTokenResponse.Merge(dst, src)
}
func (m *GeneratePasswordTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GeneratePasswordTokenResponse.Size(m)
}
func (m *GeneratePasswordTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratePasswordTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratePasswordTokenResponse proto.InternalMessageInfo

func (m *GeneratePasswordTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResetPasswordRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{9}
}
func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (dst *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(dst, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ConfirmAccountRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmAccountRequest) Reset()         { *m = ConfirmAccountRequest{} }
func (m *ConfirmAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmAccountRequest) ProtoMessage()    {}
func (*ConfirmAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{10}
}
func (m *ConfirmAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmAccountRequest.Unmarshal(m, b)
}
func (m *ConfirmAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmAccountRequest.Marshal(b, m, deterministic)
}
func (dst *ConfirmAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmAccountRequest.Merge(dst, src)
}
func (m *ConfirmAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmAccountRequest.Size(m)
}
func (m *ConfirmAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmAccountRequest proto.InternalMessageInfo

func (m *ConfirmAccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CreateAccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{11}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Account              *Account `protobuf:"bytes,4,opt,name=account" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{12}
}
func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(dst, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type DeleteAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{13}
}
func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(dst, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_06cee499b08ebed0, []int{14}
}
func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(dst, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Address)(nil), "account.Address")
	proto.RegisterType((*Account)(nil), "account.Account")
	proto.RegisterMapType((map[string]string)(nil), "account.Account.MetadataEntry")
	proto.RegisterType((*ListAccountsRequest)(nil), "account.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "account.ListAccountsResponse")
	proto.RegisterType((*GetByIdRequest)(nil), "account.GetByIdRequest")
	proto.RegisterType((*GetByEmailRequest)(nil), "account.GetByEmailRequest")
	proto.RegisterType((*AuthenticateByEmailRequest)(nil), "account.AuthenticateByEmailRequest")
	proto.RegisterType((*GeneratePasswordTokenRequest)(nil), "account.GeneratePasswordTokenRequest")
	proto.RegisterType((*GeneratePasswordTokenResponse)(nil), "account.GeneratePasswordTokenResponse")
	proto.RegisterType((*ResetPasswordRequest)(nil), "account.ResetPasswordRequest")
	proto.RegisterType((*ConfirmAccountRequest)(nil), "account.ConfirmAccountRequest")
	proto.RegisterType((*CreateAccountRequest)(nil), "account.CreateAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "account.UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "account.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "account.DeleteAccountResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*Account, error)
	GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*Account, error)
	AuthenticateByEmail(ctx context.Context, in *AuthenticateByEmailRequest, opts ...grpc.CallOption) (*Account, error)
	GeneratePasswordToken(ctx context.Context, in *GeneratePasswordTokenRequest, opts ...grpc.CallOption) (*GeneratePasswordTokenResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*Account, error)
	ConfirmAccount(ctx context.Context, in *ConfirmAccountRequest, opts ...grpc.CallOption) (*Account, error)
	Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) List(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetByEmail(ctx context.Context, in *GetByEmailRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/GetByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AuthenticateByEmail(ctx context.Context, in *AuthenticateByEmailRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/AuthenticateByEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GeneratePasswordToken(ctx context.Context, in *GeneratePasswordTokenRequest, opts ...grpc.CallOption) (*GeneratePasswordTokenResponse, error) {
	out := new(GeneratePasswordTokenResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/GeneratePasswordToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ConfirmAccount(ctx context.Context, in *ConfirmAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/ConfirmAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Update(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account.AccountService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Delete(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	List(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	GetById(context.Context, *GetByIdRequest) (*Account, error)
	GetByEmail(context.Context, *GetByEmailRequest) (*Account, error)
	AuthenticateByEmail(context.Context, *AuthenticateByEmailRequest) (*Account, error)
	GeneratePasswordToken(context.Context, *GeneratePasswordTokenRequest) (*GeneratePasswordTokenResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*Account, error)
	ConfirmAccount(context.Context, *ConfirmAccountRequest) (*Account, error)
	Create(context.Context, *CreateAccountRequest) (*Account, error)
	Update(context.Context, *UpdateAccountRequest) (*Account, error)
	Delete(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).List(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetById(ctx, req.(*GetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GetByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetByEmail(ctx, req.(*GetByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AuthenticateByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AuthenticateByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/AuthenticateByEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AuthenticateByEmail(ctx, req.(*AuthenticateByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GeneratePasswordToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePasswordTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GeneratePasswordToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/GeneratePasswordToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GeneratePasswordToken(ctx, req.(*GeneratePasswordTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ConfirmAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ConfirmAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ConfirmAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ConfirmAccount(ctx, req.(*ConfirmAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Update(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Delete(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _AccountService_List_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _AccountService_GetById_Handler,
		},
		{
			MethodName: "GetByEmail",
			Handler:    _AccountService_GetByEmail_Handler,
		},
		{
			MethodName: "AuthenticateByEmail",
			Handler:    _AccountService_AuthenticateByEmail_Handler,
		},
		{
			MethodName: "GeneratePasswordToken",
			Handler:    _AccountService_GeneratePasswordToken_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _AccountService_ResetPassword_Handler,
		},
		{
			MethodName: "ConfirmAccount",
			Handler:    _AccountService_ConfirmAccount_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/account/proto/account.proto",
}

func init() {
	proto.RegisterFile("services/account/proto/account.proto", fileDescriptor_account_06cee499b08ebed0)
}

var fileDescriptor_account_06cee499b08ebed0 = []byte{
	// 678 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x4f, 0x13, 0x4d,
	0x14, 0xa5, 0xa5, 0x6f, 0xdc, 0xe7, 0x69, 0xc5, 0xcb, 0x12, 0x9a, 0x15, 0x08, 0x19, 0x94, 0xa0,
	0x51, 0x30, 0xf8, 0x12, 0x03, 0x7e, 0xe1, 0x2d, 0x48, 0xa2, 0x04, 0x17, 0xfd, 0x6a, 0x33, 0x76,
	0xaf, 0xb2, 0xa1, 0xdd, 0xad, 0x3b, 0x53, 0x14, 0xfe, 0x9e, 0xff, 0xc1, 0xdf, 0x63, 0x76, 0x66,
	0x76, 0xbb, 0x6d, 0xa7, 0xc5, 0x4f, 0x9d, 0x7b, 0xe7, 0xdc, 0x3b, 0x67, 0xee, 0x9c, 0xb3, 0x85,
	0x87, 0x82, 0xe2, 0xeb, 0xa0, 0x4d, 0x62, 0x9b, 0xb7, 0xdb, 0x51, 0x3f, 0x94, 0xdb, 0xbd, 0x38,
	0x92, 0x51, 0x1a, 0x6d, 0xa9, 0x08, 0xab, 0x26, 0x64, 0xeb, 0x50, 0xdd, 0xf7, 0xfd, 0x98, 0x84,
	0xc0, 0x26, 0x54, 0xb9, 0x5e, 0x36, 0x0b, 0x6b, 0x85, 0xcd, 0x39, 0x2f, 0x0d, 0xd9, 0xef, 0x22,
	0x54, 0xf7, 0x75, 0x01, 0x36, 0xa0, 0x18, 0xf8, 0x06, 0x50, 0x0c, 0x7c, 0x44, 0x28, 0x85, 0xbc,
	0x4b, 0xcd, 0xa2, 0xca, 0xa8, 0x35, 0x3a, 0x50, 0xa6, 0x2e, 0x0f, 0x3a, 0xcd, 0x59, 0x95, 0xd4,
	0x01, 0x6e, 0xc1, 0x9c, 0x69, 0x48, 0xa2, 0x59, 0x5a, 0x9b, 0xdd, 0xfc, 0x6f, 0x67, 0x7e, 0x2b,
	0xa5, 0x65, 0x48, 0x78, 0x03, 0x08, 0xae, 0x43, 0xbd, 0x1d, 0x85, 0xdf, 0x82, 0xb8, 0xdb, 0x92,
	0xd1, 0x15, 0x85, 0xcd, 0xb2, 0xea, 0xf6, 0xbf, 0x49, 0x7e, 0x4a, 0x72, 0xf8, 0x1c, 0x9c, 0x1e,
	0x17, 0xe2, 0x67, 0x14, 0xfb, 0xad, 0x98, 0x04, 0x49, 0x83, 0xad, 0x28, 0x2c, 0xa6, 0x7b, 0x5e,
	0xb2, 0xa5, 0x2b, 0x76, 0xa1, 0xd6, 0x25, 0xc9, 0x7d, 0x2e, 0x79, 0xb3, 0xaa, 0x58, 0xac, 0x0e,
	0x58, 0x98, 0xdf, 0x0f, 0x06, 0x70, 0x1c, 0xca, 0xf8, 0xc6, 0xcb, 0xf0, 0xee, 0x1e, 0xd4, 0x87,
	0xb6, 0x70, 0x1e, 0x66, 0xaf, 0xe8, 0xc6, 0x8c, 0x23, 0x59, 0x26, 0x77, 0xbf, 0xe6, 0x9d, 0x7e,
	0x3a, 0x10, 0x1d, 0xec, 0x16, 0xdf, 0x14, 0xd8, 0x47, 0x58, 0x78, 0x1f, 0x08, 0x69, 0xce, 0x10,
	0x1e, 0xfd, 0xe8, 0x93, 0x90, 0xf8, 0x00, 0xe6, 0x7a, 0xfc, 0x3b, 0xb5, 0x44, 0x70, 0x4b, 0xaa,
	0x51, 0xd9, 0xab, 0x25, 0x89, 0x8b, 0xe0, 0x96, 0x70, 0x05, 0x40, 0x6d, 0xea, 0x4b, 0xe9, 0x96,
	0x0a, 0xae, 0xee, 0xc2, 0x3a, 0xe0, 0x0c, 0xb7, 0x14, 0xbd, 0x28, 0x14, 0x84, 0x4f, 0xa1, 0x66,
	0xae, 0x94, 0xbc, 0xe5, 0xc8, 0xa4, 0xf5, 0xaf, 0x97, 0x21, 0x70, 0x03, 0xee, 0x85, 0xf4, 0x4b,
	0xb6, 0xc6, 0x4e, 0xaa, 0x27, 0xe9, 0xf3, 0xec, 0xb4, 0x35, 0x68, 0x9c, 0x90, 0x3c, 0xb8, 0x39,
	0xf5, 0x53, 0xee, 0x23, 0x62, 0x60, 0x8f, 0xe1, 0xbe, 0x42, 0x1c, 0x27, 0x0f, 0x9e, 0x82, 0x32,
	0x35, 0x14, 0x72, 0x6a, 0x60, 0x67, 0xe0, 0xee, 0xf7, 0xe5, 0x25, 0x85, 0x32, 0x68, 0x73, 0x49,
	0xff, 0x52, 0x83, 0x2e, 0xd4, 0xd2, 0x07, 0x35, 0x0c, 0xb3, 0x98, 0xbd, 0x84, 0xe5, 0x13, 0x0a,
	0x29, 0xe6, 0x92, 0xce, 0x4d, 0x4e, 0xb1, 0x9e, 0xce, 0xe2, 0x15, 0xac, 0x4c, 0xa8, 0x32, 0x93,
	0x74, 0xa0, 0xac, 0x27, 0x62, 0xca, 0x54, 0xc0, 0xde, 0x81, 0xa3, 0x14, 0x75, 0x9e, 0xc9, 0x2b,
	0x3b, 0x64, 0x1c, 0x3d, 0x95, 0xf6, 0x33, 0x58, 0x3c, 0xd4, 0x7a, 0x4e, 0xdf, 0x65, 0x5a, 0x2b,
	0xf6, 0x05, 0x9c, 0xc3, 0x98, 0xb8, 0xa4, 0x11, 0xf4, 0x13, 0x48, 0x1d, 0xad, 0xf0, 0xb6, 0xf7,
	0x4e, 0x01, 0x53, 0xe9, 0x84, 0xe0, 0x7c, 0xee, 0xf9, 0xe3, 0xfd, 0x47, 0x5d, 0x3f, 0xa5, 0x47,
	0x9e, 0x4b, 0xe9, 0x0e, 0x2e, 0x6c, 0x03, 0x9c, 0x23, 0xea, 0xd0, 0x5d, 0xe7, 0xb1, 0x25, 0x58,
	0x1c, 0xc1, 0xe9, 0xf7, 0xd9, 0xf9, 0x53, 0x86, 0x86, 0xc9, 0x5d, 0xe8, 0x0f, 0x1f, 0x1e, 0x43,
	0x29, 0x31, 0x05, 0x2e, 0x67, 0xc7, 0x5a, 0x6c, 0xe7, 0xae, 0x4c, 0xd8, 0xd5, 0x7d, 0xd9, 0x0c,
	0xbe, 0x86, 0xaa, 0x51, 0x3b, 0x2e, 0x65, 0xd8, 0x61, 0xfd, 0xbb, 0x63, 0x37, 0x63, 0x33, 0xf8,
	0x16, 0x60, 0xe0, 0x01, 0x74, 0x87, 0x4b, 0xf3, 0x22, 0xb7, 0x56, 0x9f, 0xc1, 0x82, 0xc5, 0x16,
	0xb8, 0x3e, 0x80, 0x4e, 0x34, 0x8d, 0xb5, 0xdf, 0x25, 0x2c, 0x5a, 0x05, 0x8e, 0x8f, 0x72, 0xc4,
	0x26, 0xdb, 0xc6, 0xdd, 0xb8, 0x0b, 0x96, 0xcd, 0xeb, 0x00, 0xea, 0x43, 0x9e, 0xc0, 0xc1, 0x84,
	0x6d, 0x5e, 0xb1, 0xb2, 0x3d, 0x82, 0xc6, 0xb0, 0x1b, 0x70, 0xf0, 0x6d, 0xb6, 0xda, 0xc4, 0xda,
	0x65, 0x0f, 0x2a, 0xda, 0x24, 0x39, 0x0a, 0x36, 0xd7, 0x4c, 0x2a, 0xd6, 0x0e, 0xc8, 0x15, 0xdb,
	0x2c, 0x61, 0x2d, 0x3e, 0x85, 0x8a, 0x96, 0x69, 0xae, 0xd8, 0xa6, 0x6f, 0x77, 0x75, 0xd2, 0x76,
	0x3a, 0xce, 0xaf, 0x15, 0xf5, 0x47, 0xfd, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x15, 0x82,
	0x49, 0xd5, 0xd0, 0x07, 0x00, 0x00,
}
